export const NEWS_ACTION_TYPES = {
    FETCH_NEWS_START: 'news/FETCH_NEWS_START',
    FETCH_NEWS_SUCCESS: 'news/FETCH_NEWS_SUCCESS',
    FETCH_NEWS_FAILED: 'news/FETCH_NEWS_FAILED',
    FETCH_NEWS_BY_EVERYTHING_START: 'news/FETCH_NEWS_BY_EVERYTHING_START',
    FETCH_NEWS_BY_EVERYTHING_SUCCESS: 'news/FETCH_NEWS_BY_EVERYTHING_SUCCESS',
    FETCH_NEWS_BY_EVERYTHING_FAILED: 'news/FETCH_NEWS_BY_EVERYTHING_FAILED',
    SET_CURRENT_PAGE: 'news/SET_CURRENT_PAGE',
};
